### ISSUE TITLE
feature: 添加背景图片

### ISSUE THREAD

**Issue by ThymeiWonder** [ThymeiWonder/theme.typora.iWonder#4]
1. 文档全局的背景图片
2. 文档内容区右下角的背景图片

**Comment by caolib** [comment]
### 你好，我尝试添加了一下，大概是这个效果

![Image](https://github.com/user-attachments/assets/1e8fc1d8-f0d6-49db-916f-c4873652bffc)

1. 修改`highlighter.css`文件，在第30行左右，修改背景为透明
```css
/* 内容区背景透明 */
#write {
    background-color: transparent;
}
```

2. 然后在`i-w-blue.css`文件添加下面内容以显示图片（注意替换图片的路径，size可调整大小）
```css
/* 主界面背景图片 */
content {
    background-color: transparent;
    background-image: url('./iWonder/img/bg.gif');
    background-position: 100% 100%;
    background-repeat: no-repeat;
    background-size: 200px auto;
    transition: background-image .5s ease-in-out, background-size .5s ease-in-out
}
```

3. 添加一个文件夹把图片放进去
